Repository yessGlory17/nft-marketplace, pull requests merged in 2022-01, with the labels that each got.

#1 login button and login functions
  package-lock.json
  package.json
  src/components/Header.js
  src/components/Hero.js
  src/constants/MockupData.js
  src/index.js
Labels: enhancement

#2 search component
  src/styles/Explore.css
  src/styles/Hero.css
  src/styles/Search.css
Labels: enhancement

#11 Creating the contribution guide
  CONTRIBUTING.md
  assets/clone.png
  assets/fork.png
  assets/pull.png
Labels: documentation

#19 fixed the moving of navbar-tabs on hovering
  src/styles/Hero.css
Labels: bug

#25 base card
  src/components/Filters.js
  src/components/NFTCard.js
  src/components/base/Card.js
  src/components/base/Input.js
  src/styles/Filters.css
  src/styles/base/Card.css
  src/styles/base/Input.css
Labels: enhancement

#27 made navbar-fixed & improved the design
  public/index.html
  src/styles/Hero.css
Labels: enhancement

#28 Base components
  docs/design/BaseComponents.md
  docs/images/base/accordion-basic.png
  docs/images/base/accordion-child-example.png
  docs/images/base/button-basic-example.png
  docs/images/base/button-color-example.png
  docs/images/base/button-textColor-example.png
  docs/images/base/car-child-example.png
  docs/images/base/card-basic-example.png
  docs/images/base/card-blurColor-example.png
  docs/images/base/checkbox-name-example.png
  docs/images/base/image-basic-example.png
  docs/images/base/select-after-example.png
  docs/images/base/select-after-select-example.png
  docs/images/base/select-before-example.png
  docs/images/base/textinput-basic-example.png
  docs/images/base/textinput-icon-example.png
  docs/images/base/textinput-placeholder-example.png
  src/components/Card.js
  src/components/CardList.js
  src/components/Filters.js
  src/components/NFTCard.js
  src/components/Search.js
  src/components/base/Accordion.js
  src/components/base/AccordionHeader.js
  src/components/base/Button.js
  src/components/base/Card.js
  src/components/base/Checkbox.js
  src/components/base/Image.js
  src/components/base/Select.js
  src/components/base/TextInput.js
  src/constants/Colors.js
  src/pages/Create.js
  src/pages/Home.js
  src/styles/Filters.css
  src/styles/NFTCard.css
  src/styles/base/AccordionHeader.css
  src/styles/base/Button.css
  src/styles/base/Card.css
  src/styles/base/Checkbox.css
  src/styles/base/Image.css
  src/styles/base/Input.css
  src/styles/base/Select.css
  src/styles/base/TextInput.css
Labels: enhancement
